packages:
  - packages/api-express
  - packages/api-fastify
  - packages/api-hapi
  - packages/api-hono
  - packages/api-koa
  - packages/api-nestjs
  - packages/cli
  - packages/parser

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - '@nestjs/core'
