packages:
  - packages/api-express
  - packages/api-hono
  - packages/api-koa
  - packages/api-nestjs
  - packages/api-vercel
  - packages/cli
  - packages/parser

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - '@nestjs/core'
